### ISSUE TITLE
metrics: baremetal slave nodes seem to lose connection with jenkins 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#138]
most of the metrics jobs are failing with this error: 

```
08:26:30 FATAL: java.io.IOException: Unexpected termination of the channel
08:26:30 java.io.EOFException
08:26:30 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
08:26:30 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
08:26:30 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
08:26:30 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
08:26:30 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
08:26:30 	at hudson.remoting.Command.readFrom(Command.java:140)
08:26:30 	at hudson.remoting.Command.readFrom(Command.java:126)
08:26:30 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
08:26:30 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
08:26:30 Caused: java.io.IOException: Unexpected termination of the channel
08:26:30 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
08:26:30 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to x86_packet02
08:26:30 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
08:26:30 		at hudson.remoting.Request.call(Request.java:202)
08:26:30 		at hudson.remoting.Channel.call(Channel.java:956)
08:26:30 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
08:26:30 		at com.sun.proxy.$Proxy394.withRepository(Unknown Source)
08:26:30 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:237)
08:26:30 		at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1263)
08:26:30 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1236)
08:26:30 		at hudson.scm.SCM.checkout(SCM.java:504)
08:26:30 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
08:26:30 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
08:26:30 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
08:26:30 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
08:26:30 		at hudson.model.Run.execute(Run.java:1816)
08:26:30 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
08:26:30 		at hudson.model.ResourceController.execute(ResourceController.java:97)
08:26:30 		at hudson.model.Executor.run(Executor.java:429)
08:26:30 Caused: hudson.remoting.RequestAbortedException
08:26:30 	at hudson.remoting.Request.abort(Request.java:340)
08:26:30 	at hudson.remoting.Channel.terminate(Channel.java:1040)
08:26:30 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:94)
```

/cc @grahamwhaley any idea if there could be network issues with these nodes?

**Comment by grahamwhaley** [comment]
I went to have a look at the slave build history http://jenkins.katacontainers.io/computer/x86_packet02/builds
There does seem to have been a series of fails about 18-22h ago, but things look to have settled down now.
Yes, those java dumps are the jenkins connection getting upset - normally as the job has failed in some way it does not understand. Here is a snippet from the last fail on the slave, which looks like the nemu install failed.

Generally you need to ignore all the java stack stuff, and scroll back up to see what actually upset it.
Hmm, so, in cases like the below (where it wholly appears the install of nemu failed), we should see if there is something we are doing that is preventing further, more useful, errors coming out. I would have thought `chronic` for instance would do the right thing on a fail...

```
22:55:38 Install nemu dependencies
22:55:38 FATAL: command execution failed
22:55:38 java.io.EOFException
22:55:38 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
22:55:38 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
22:55:38 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
22:55:38 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
22:55:38 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
22:55:38 	at hudson.remoting.Command.readFrom(Command.java:140)
22:55:38 	at hudson.remoting.Command.readFrom(Command.java:126)
22:55:38 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
22:55:38 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
22:55:38 Caused: java.io.IOException: Unexpected termination of the channel
```

**Comment by grahamwhaley** [comment]
Guess this was fixed - not seen it again. spurios. closing.
