### ISSUE TITLE
ARM CI timing out on `check dnf update` test

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/ci#245]
# Description of problem
Hi guys
So sorry about recent unstable state on ARM CI. 😭
For now, ARM CI is suddenly failing on `check dnf update` docker test. 
http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/1472/
```
08:25:58 [Serial Test] package manager update test check dnf update 
08:25:58   should not fail
08:25:58   /home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:72
08:25:58 Running command '/usr/bin/docker [docker run --cidfile /tmp/cid199354545/8RUvK4eZckYIrYdMsKOaKJPSB0pr11 --runtime kata-runtime -td --name 8RUvK4eZckYIrYdMsKOaKJPSB0pr11 fedora sh]'
08:26:00 [docker run --cidfile /tmp/cid199354545/8RUvK4eZckYIrYdMsKOaKJPSB0pr11 --runtime kata-runtime -td --name 8RUvK4eZckYIrYdMsKOaKJPSB0pr11 fedora sh]
08:26:00 Timeout: 120 seconds
08:26:00 Exit Code: 0
08:26:00 Stdout: f7e96ceeeeecaab02ed27934470b9f2c2a1ebc1a498022d959a5e214802cf099
08:26:00 
08:26:00 Stderr: 
08:26:00 Running command '/usr/bin/docker [docker exec 8RUvK4eZckYIrYdMsKOaKJPSB0pr11 dnf -y update]'
08:27:00 .
08:28:00 .
08:29:00 .
08:30:00 .
08:31:00 .
08:32:00 .
08:33:00 .
08:34:00 .
08:35:00 .
08:36:00 .
08:37:00 .
08:38:00 .
08:39:00 .
08:40:00 .
08:41:00 Killing process timeout reached '900' seconds
08:41:00 Running command '/usr/bin/docker [docker exec 8RUvK4eZckYIrYdMsKOaKJPSB0pr11 dnf -y update]'
08:41:09 command failed error 'exit status 1'
08:41:09 [docker exec 8RUvK4eZckYIrYdMsKOaKJPSB0pr11 dnf -y update]
08:41:09 Timeout: 900 seconds
08:41:09 Exit Code: 1
08:41:09 Stdout: 
08:41:09 Stderr: Traceback (most recent call last):
08:41:09   File "/usr/bin/dnf", line 57, in <module>
08:41:09     from dnf.cli import main
08:41:09   File "/usr/lib/python3.7/site-packages/dnf/__init__.py", line 30, in <module>
08:41:09     import dnf.base
08:41:09   File "/usr/lib/python3.7/site-packages/dnf/base.py", line 44, in <module>
08:41:09     import dnf.conf
08:41:09   File "/usr/lib/python3.7/site-packages/dnf/conf/__init__.py", line 40, in <module>
08:41:09     from dnf.conf.config import PRIO_DEFAULT, PRIO_MAINCONFIG, PRIO_AUTOMATICCONFIG
08:41:09   File "/usr/lib/python3.7/site-packages/dnf/conf/config.py", line 33, in <module>
08:41:09     import hawkey
08:41:09   File "/usr/lib64/python3.7/site-packages/hawkey/__init__.py", line 33, in <module>
08:41:09     from . import _hawkey
08:41:09 ImportError: /usr/lib64/python3.7/site-packages/hawkey/_hawkey.so: undefined symbol: _ZN6libdnf5QueryC1EP8_DnfSacki
```

It constantly timed out on `check dnf update`, and I had no clue on the cause of it. 
**_More importantly,  I could not reproduce this error on my local machine, it worked well there._**

```t
$ ./ginkgo -failFast -v -focus "check dnf update" ./integration/docker/ -- -runtime=kata-runtime -timeout=120
[Serial Test] package manager update test check dnf update
  should not fail
  /root/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:72
Running command '/usr/bin/docker [docker run --cidfile /tmp/cid051045149/toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 --runtime kata-runtime -td --name toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 fedora sh]'
[docker run --cidfile /tmp/cid051045149/toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 --runtime kata-runtime -td --name toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 fedora sh]
Timeout: 120 seconds
Exit Code: 0
Stdout: 4296818da5ca49b0afd976934ff9ce85a06dd3c45022f38b71568ef94465ed07

Stderr:
Running command '/usr/bin/docker [docker exec toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 dnf -y update]'
.
.
[docker exec toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 dnf -y update]
Timeout: 900 seconds
Exit Code: 0
Stdout: Fedora Modular 31 - aarch64                     2.1 MB/s | 5.2 MB     00:02
Fedora Modular 31 - aarch64 - Updates           2.1 MB/s | 3.9 MB     00:01
Fedora 31 - aarch64 - Updates                   1.0 MB/s |  18 MB     00:16
                                                 ...........
                                                 ...........
  pixman-0.38.4-1.fc31.aarch64
  rest-0.8.1-6.fc31.aarch64
  trousers-lib-0.3.13-13.fc31.aarch64

Complete!

Stderr:
Running command '/usr/bin/docker [docker rm -f toImx5OiiNdgOsW1kGGMIUK4Hi42Y1]'
[docker rm -f toImx5OiiNdgOsW1kGGMIUK4Hi42Y1]
Timeout: 120 seconds
Exit Code: 0
Stdout: toImx5OiiNdgOsW1kGGMIUK4Hi42Y1

Stderr:
Running command '/usr/bin/docker [docker ps -a -f name=toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 --format {{.Status}}]'
[docker ps -a -f name=toImx5OiiNdgOsW1kGGMIUK4Hi42Y1 --format {{.Status}}]
Timeout: 120 seconds
Exit Code: 0
Stdout:
Stderr:

• [SLOW TEST:157.216 seconds]
[Serial Test] package manager update test
/root/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:33
  check dnf update
  /root/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:71
    should not fail
    /root/go/src/github.com/kata-containers/tests/integration/docker/package_manager_test.go:72
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 250 Specs in 178.626 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 249 Skipped
PASS

Ginkgo ran 1 suite in 3m1.339894136s
Test Suite Passed
```

So It's the network issue???? 😖 any idea??? @kata-containers/ci

**Comment by chavafg** [comment]
ARM CI was working, seems that this was fixed time ago. Closing.
